name: deps

on:
  push:
    # branches: [seismic]
  pull_request:
    # branches: [seismic]
  # schedule: [cron: "00 00 * * *"]

jobs:
  cargo-deny:
    name: cargo deny check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check all
