name: Seismic CI

on:
  push:
    branches: [ use-mantle-git-commit ]
  pull_request:
    branches: [ seismic ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true


jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  # Define the common steps using YAML anchors
  # The '&setup-steps' defines an anchor named 'setup-steps' that can be referenced later
  _setup: &setup-steps
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Install SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.ACTIONS_MANTLE_SSH_ED25519 }}
          ${{ secrets.ACTIONS_SFORGESTD_SSH_ED25519 }}

  cargo-check-warnings:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Reference the shared steps using '*setup-steps'
      <<: *setup-steps
      - name: Cargo Check with Warnings
        run: RUSTFLAGS="-D warnings" cargo check

  cargo-test:
    needs: cargo-check-warnings
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Reference the shared steps again
      <<: *setup-steps
      - name: Cargo Test
        run: cargo test