name: Seismic CI

on:
  push:
    branches: [ use-mantle-git-commit ]
  pull_request:
    branches: [ seismic ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  install-ssh-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Install Mantle SSH Key
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.ACTIONS_MANTLE_SSH_ED25519 }}
          name: id_ed25519_mantle
          known_hosts: github.com

  cargo-fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  cargo-check-warnings:
    needs: install-ssh-keys
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: RUSTFLAGS="-D warnings" cargo check

  cargo-test:
    needs: install-ssh-keys
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo test
